---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: 'metron'
  subject:
    organizations:
      - metron
  secretName: root-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - '*.equinox.caci.com'
    - 'belltower.equinox.caci.com'
    - 'keycloak.equinox.caci.com'
    - 'gitlab.equinox.caci.com'
    - 'harbor.equinox.caci.com'
  ipAddresses:
    - 10.216.148.139
    - 10.216.148.22
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: root-secret