---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: httpbin
spec:
  secretName: wildcard-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: 'wildcard'
  subject:
    organizations:
      - metron
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - '*.ky-rafaels.com'
    - 'grafana.ky-rafaels.com'
    - 'hubble.ky-rafaels.com'
    - 'keycloak.ky-rafaels.com'
    - 'httpbin.ky-rafaels.com'
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io