---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: gitlab-postgresql-password
  namespace: gitlab
spec:
  encryptedData:
    postgresql-password: AgAXAH8SmGh0Bd1hiEHaMDa0RiKbmv401n9zFNddxvFS23CTBVlprCBvx+P8otLdEHcd9y0lGTJhwrbs7+q0/eyvE4DrfbajhWFdJn+H1NezDSGH6BZGAtTw7umuZVV8lGzRvVd8n6Dr/tpOB0proJMrh0vj2t969PM50KAQVyvgeECon3O8DG69B/h90GB9H60QeEcRF0nsX9z3CLhyVZ/OObhRNGyl+C94qnfw3jWLBRjuUvEjfNcz1PZYefQ5cctKHAjLDPI12BrTHPjSEP3Sj50x1HsGRcon+wCfzGLbuAxoR7fXnIQ+Rjzn57Egg4ZeKwo6m0G5GEzPbbafBN3gmBRj0OW7u7/w7qEQmxpbkNAGa/wQdFx02x61d1r4Nsh1jN6+Wrvbn1ntQGvttmJzENSoXcxiBgFgkPlFwqY+gZBkp9zc4Foytm9IXzuCZdwMU6nMv+HcBwCfDB62jUJyj98gg2X1+1rwphjMZ7FwxGwASFTLopd2tHT8FKUyyxBC6bkYEmbTFHgNSeqCYknQU/yI8vdhIxyKFX1K8YkLxRMFznMsvd5nTSC2A/Yf/8MW0SfSovGccwuLMaNknxGK7LWg2TIFsLDAKfcz3hM0vUVomvLTXStLG2EZz67+l2xXcqJhx/S/h1UCZ80OtBz1y32C6pPE6D2q0h22YRYugNcYhNAbxkw31qpK/CDdYy8v2HDJ8Pdb
    postgresql-postgres-password: AgBqGEmIJe+MAvyJqCnDfZNGdutZ4Uj12iXD8f0/t29ZTXKFiANPuW6HNCscxKACmQhCa/yW5E3bHVEPaBH/xLTyclk5CXOux6DiRmyE0ng/G7Vw7frMq13n4zjVmhIKYom+rDhsV+fOaoEkxREeYf5LSZHWxmIaSOCP2Z5af8RvxxyFUV+8GkDzDoWsemubEaPiVlGnQ8VdyIFcy3jsseyi8r+B4U29OS1+wufmYSC35hpQSb6VogkSW1arJgtQ53Dc+yAJ+6zzO9FLfntJpd6Zy+YWKreG6vOqw800JY6xb5W09hN6iuEXLXaiRPck97Norc2FSwZjEfKhX8Hco6RvUlO8IJhL+OlRHPjCC2L48tHIert+QzCmn0zduR0XrlDioFZcLLRDgCjbyaXX/89FbHhq4IRghM0TqJ+ZoteGRsaPVBQBvbTIgl+3qubde+biuAvVVC5gY0973xWledyNlTtpZfi8OamHWp04nUmZk7qjMK9gntfHhkPW4svYoQajOS2mGHAzv2QqFUQejH5FQsi7U9WniapaXbph/sdBK7Y3fKBLwfGV2FljpQXADsW3gyzaoWhuIrvw3UZJ5pTwF/g4/7eaifPCdnJqIgvYg1j8kZBbnDM4oEFcjY75Fr4cg1/f/IvE4+kWJliXFoLFx9BiHv4ivGB4Aaiy0/MKZ3fknrQ50kKiE9euzhsoMKE4mJ2+UakN
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: gitlab-postgresql-password
      namespace: gitlab
    type: Opaque