apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../base"

images:
- name: quay.io/keycloak/keycloak:21.0.2
  newName: harbor.csde.caci.com/docker.io/chainguard/keycloak
  newTag: latest