---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: belltower
  namespace: web-ui
spec:
  parentRefs:
  - name: gateway
    namespace: httpbin
    sectionName: passthrough-tls
  hostnames: 
  - 'belltower.equinox.caci.com'
  rules:
  - backendRefs:
    - name: web-ui
      namespace: web-ui
      port: 8443