apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../base"

images:
  - name: registry.k8s.io/metrics-server/metrics-server:v0.7.0
    newName: harbor.csde.caci.com/docker.io/chainguard/metrics-server
    newTag: latest