---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitlab
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/ky-rafaels/gitops-k8s-platform.git'
    path: k8s/shared-services/gitlab
    targetRevision: main
    helm:
      valueFiles:
      - caci-values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true