---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: harbor
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://gitlab.csde.caci.com/Equinox/belltower-deploy.git'
    path: k8s/shared-services/harbor
    targetRevision: main
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
      - values.yaml
      - caci-values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true