---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keycloak
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'git@github.com:ky-rafaels/gitops-k8s-platform.git'
    path: k8s/shared-services/keycloak/charts/keycloak
    targetRevision: main
    helm:
      valueFiles:
      - values.yaml
      - custom-values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true