---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - clusters: {} 
  template:
    metadata:
      name: 'cert-manager'
    spec:
      project: default
      source: 
        repoURL: 'https://gitlab.csde.caci.com/Equinox/belltower-deploy.git' 
        targetRevision: main 
        path: k8s/supporting-components/cert-manager/helm/cert-manager
        helm:
          releaseName: cert-manager
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - caci-values.yaml
      destination:
        name: "in-cluster"
        namespace: 'cert-manager'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true