---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  generators:
    - clusters: {} 
  template:
    metadata:
      name: "istio-ingress"
    spec:
      project: default
      source: 
        repoURL: 'https://gitlab.csde.caci.com/Equinox/belltower-deploy.git' 
        targetRevision: main
        path: k8s/supporting-components/istio/1.22/istio-ingress
        helm:
          releaseName: istio-ingress
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            # - values-{{ env }}.yaml
      destination:
        name: "in-cluster"
        namespace: 'istio-ingress'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true

## Example not using appset
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: istio-ingress
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: 'https://istio-release.storage.googleapis.com/charts'
#     targetRevision: 1.19.1
#     helm:
#       parameters:
#         - name: revision
#           value: 1-22
#       values: |-
#         labels:
#           istio: ingressgateway
#           istio.io/rev: 1-22
#         annotations:
#           proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
#     chart: gateway
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: istio-ingress
#   syncPolicy:
#     automated:
#       prune: true
#     syncOptions:
#       - CreateNamespace=true
#       - ApplyOutOfSyncOnly=true
