---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keda
  namespace: argocd
spec:
  generators:
    - clusters: {} 
  template:
    metadata:
      name: 'keda'
    spec:
      project: default
      source: 
        repoURL: 'git@github.com:ky-rafaels/gitops-k8s-platform.git' 
        targetRevision: main
        path: k8s/supporting-components/keda/
        helm:
          releaseName: keda
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - custom-values.yaml
      destination:
        name: "in-cluster"
        namespace: 'keda'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true