---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-telemetry
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: open-telemetry
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'git@github.com:ky-rafaels/gitops-k8s-platform.git'
    path: k8s/supporting-components/opentelemetry-collector/
    targetRevision: main
    helm:
      valueFiles:
      - caci-values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true