---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://gitlab.csde.caci.com/Equinox/belltower-deploy.git'
    path: k8s/supporting-components/sealed-secrets
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false