---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: analytic
  namespace: argocd
spec:
  generators:
    - clusters: {} 
  template:
    metadata:
      name: 'analytic'
    spec:
      project: default
      source: 
        repoURL: 'https://gitlab.csde.caci.com/Equinox/belltower-deploy.git' 
        targetRevision: main
        path: k8s/belltower-apps/analytic
      destination:
        name: "in-cluster"
        namespace: 'analytic'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true