apiVersion: v1
data:
  ipc.yaml: "# common config needed for ipc\n# loaded by spring.config.import=ipc.yaml
    in application.yaml files\n---\nspring:\n  data:\n    mongodb:\n      database:
    belltower\n  rabbitmq:\n    template: # refers to spring's RabbitTemplate, not
    to BellTowerTemplate\n      retry:\n        enabled: true\n    listener:\n      #
    run listeners on the rabbit IO thead\n      type: direct\n---\n# set host names
    when running inside docker compose\nspring:\n  config:\n    activate:\n      on-profile:
    docker-compose\n  data:\n    mongodb:\n      host: mongo\n  rabbitmq:\n    host:
    rabbit\n\n---\n# set host names when running inside kubernetes\nspring:\n  config:\n
    \   activate:\n      on-profile: kubernetes \n  data:\n    mongodb:\n      host:
    mongo.mongo\n  rabbitmq:\n    host: rabbit.rabbitmq"
kind: ConfigMap
metadata:
  name: ipc-config
