---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbit
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbit
  name: rabbit
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: amqp-tls
      port: 5671
      targetPort: 5671
    - name: dist 
      port: 25672
      targetPort: 25672
    - name: epmd 
      port: 4369
      targetPort: 4369
    - name: manager
      port: 15672
      targetPort: 15672
    - name: metrics
      port: 9419
      targetPort: 9419
  selector:
    app: rabbit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbit
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - image: rabbitmq:3.12.13
        name: rabbit
        ports:
        - name: amqp
          containerPort: 5672
          protocol: TCP
        - name: manager
          containerPort: 15672
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 300Mi
      restartPolicy: Always
