apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: kommander 
spec:
  interval: 1h
  chart:
    spec:
      chart: gitlab
      version: ">=7.0.0"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: kommander-flux
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
  timeout: 600s
  values:
    installCertManager: false
    certmanager-issuer:
      email: kyle.rafaels@nutanix.com 
    global:
      minio:
        enabled: true
        ingress:
          tls:
            secretName: minio-tls
      edition: ce
      hosts:
        domain: kyle-lab.com
        https: true
        externalIP: 192.168.1.30
        gitlab:
          name: gitlab.kyle-lab.com
        registry:
          name: registry.kyle-lab.com
        minio:
          name: minio.kyle-lab.com

      ingress:
        provider: kommander-traefik
        enabled: true
        class: kommander-traefik
        annotations:
          kubernetes.io/ingress.class: kommander-traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        configureCertmanager: true
        tls:
          enabled: true

      certManager:
        installType: none

    nginx-ingress:
      enabled: false

    gitlab:
      webservice:
        minReplicas: 1
        maxReplicas: 1
        ingress:
          tls:
            secretName: gitlab-tls
        resources:
          requests:
            cpu: 300m
            memory: 1.5Gi
      sidekiq:
        minReplicas: 1
        maxReplicas: 1
        resources:
          requests:
            cpu: 50m
            memory: 625Mi
      gitaly:
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
      toolbox:
        enabled: true

    registry:
      enabled: true
      ingress:
        tls:
          secretName: registry-tls

    postgresql:
      install: true

    redis:
      install: true

    prometheus:
      install: false

    gitlab-runner:
      install: false