apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../base"

images:
- name: quay.io/keycloak/keycloak:21.0.2
  newName: cgr.dev/ky-rafaels.example.com/keycloak
  newTag: 26.2.1-dev