---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo 
  namespace: mongo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: mongo
spec:
  ports:
    - name: db
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: harbor.csde.caci.com/equinox/mongo:7.0.14-rc0-jammy-amd64 
        name: mongo
        ports:
        - name: db
          containerPort: 27017
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
      restartPolicy: Always
