global:
  image:
    repository: cgr.dev/ky-rafaels.example.com/argocd
    tag: 2.14.3
  # -- Secrets with credentials to pull images from a private registry
  # imagePullSecrets:
  #   - "regcred"
repoServer:
  image:
    repository: cgr.dev/ky-rafaels.example.com/argocd-repo-server
    tag: 2.14.3
dex:
  image:
    repository: cgr.dev/ky-rafaels.example.com/dex
    tag: 2.42
redis:
  image:
    repository: cgr.dev/ky-rafaels.example.com/redis
    tag: 7.2.7
server:
  extraArgs:
  - --insecure
crds:
  install: true
# configs:
#   cm:
#     dex.config: |
#       connectors:
#         - type: gitlab
#           id: gitlab
#           name: GitLab
#           config:
#             baseURL: https://gitlab....com
#             clientID: aabbccddeeff00112233
#             clientSecret: $dex.gitlab.clientSecret # Alternatively $<some_K8S_secret>:dex.github.clientSecret
#             redirectURI: http://127.0.0.1:5556/dex/callback
#             groups:
#             - developers
#             - infra
#             # flag which will switch from using the internal GitLab id to the users handle (@mention) as the user id.
#             useLoginAsID: false