---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytic
  namespace: analytic 
---
apiVersion: v1
kind: Service
metadata:
  name: analytic
  namespace: analytic
spec:
  ports:
    - name: http
      port: 4444 # temporary
      targetPort: 4444 # temporary
  selector:
    app: analytic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: analytic
  name: analytic
  namespace: analytic 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytic
  template:
    metadata:
      labels:
        app: analytic
    spec:
      serviceAccountName: analytic
      imagePullSecrets:
      - name: regcred
      containers:
      - image: harbor.csde.caci.com/equinox/analytic:corretto-11-jdk
        imagePullPolicy: Always
        args: ["--spring.profiles.active=kubernetes"]
        name: analytic
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 300Mi
      restartPolicy: Always
