---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  ports:
    - name: http
      port: 8180
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - args:
            - start
            - --optimized
            # - --import-realm
          env:
            - name: KC_DB
              value: postgres
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_DB_URL
              value: keycloak.postgres.svc.cluster.local
            - name: KC_HOSTNAME
              value: localhost
            # - name: KC_DB_USERNAME
            #   value:
            # - name: KC_DB_PASSWORD
            #   value:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            - name: KC_PROXY_HEADERS
              value: xforwarded
          image: quay.io/keycloak/keycloak:21.0.2
          name: keycloak
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          # volumeMounts:
          #   - mountPath: /opt/keycloak/data/import
          #     name: keycloak-realm
      restartPolicy: Always
      # volumes:
      #   - name: keycloak-realm
      #     configMap:
      #       name: belltower
